query GET_USER($id: ID!) {
  user(id: $id) {
    id
    firtName
  }
}

query GET_USERS {
  users {
    id
    indexRef
    firtName
    lastName
    createdAt
    updatedAt
  }
}

query GET_PHONE($id: ID!) {
  phone(id: $id) {
    id
    indexRef
    userId
    title
    value
    createdAt
    updatedAt
  }
}

query GET_PHONES {
  phones {
    id
    indexRef
    userId
    title
    value
    createdAt
    updatedAt
  }
}

# Aliases in queries

## Not using
## Not repeat property
query GET_USER($id: ID!, $id2: ID!) {
  user(id: $id) {
    id
    firtName
  }
  user(id: $id) {
    id
    firtName
  }
}

## Correct use
query GET_USER($id: ID!, $id2: ID!) {
  user(id: $id) {
    id
    firtName
  }
  aliasesUser: user(id: $id2) {
    id
    firtName
    aliasesId: id
    aliasesName: firtName
  }
}
